obj-$(CONFIG_HW_ZEROHUNG)	+= zrhung_lastword.o zrhung_transtation.o zrhung_config.o zrhung_ioctl.o zrhung_event.o watchpoint/
ifeq ($(CONFIG_ARCH_MSM),)
obj-$(CONFIG_HW_ZEROHUNG)	+= cgroup_info.o
endif
