# Hisilicon IPP v200 Makefile

EXTRA_CFLAGS += -I$(srctree)/drivers/hisi/ipp/
EXTRA_CFLAGS += -I$(srctree)/drivers/hisi/ipp/include
EXTRA_CFLAGS += -I$(srctree)/drivers/hisi/ipp/v200
EXTRA_CFLAGS += -I$(srctree)/drivers/hisi/ipp/v200/include
EXTRA_CFLAGS += -I$(srctree)/drivers/hisi/ipp/device

obj-y += cpetop.o
obj-y += mcf.o
obj-y += mfnr.o
obj-y += slam.o

