obj-$(CONFIG_WIRELESS_CHARGER) += wireless_charger.o
obj-$(CONFIG_WIRELESS_CHARGER) += wired_channel_switch/
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_otg/
obj-$(CONFIG_WIRELESS_IDTP9221) += idtp9221/