# MD5: 013adb2ee393b0bb9a792ac668f90d3f
CFG_CONFIG_LLT_MDRV := YES
CFG_CONFIG_EDMA_DEBUG := YES
CFG_CONFIG_OS_INCLUDE_LP := YES
CFG_CONFIG_RSRACC_DEBUG := YES
CFG_CPUFREQ_DEBUG_INTERFACE:=YES
CFG_CONFIG_PM_OM_DEBUG:=YES
CFG_BOARD_TRACE := YES
CFG_CONFIG_VERSION_ENG := YES
CFG_CONFIG_CSHELL := YES
CFG_CONFIG_UART_SHELL := YES
CFG_CONFIG_OS_INCLUDE_SHELL := YES
CFG_CONFIG_MEM_DEBUG := YES
CFG_CONFIG_ICC_DEBUG := YES
CFG_RFILE_PATH_CONSTRAINT_ENG := YES
