# MD5: b62cf8fc9141e3bcd4d7693919f3f114
CFG_FEATURE_AT_NV_WRITE_SUPPORT                 := YES
CFG_FEATURE_READ_LOG_FILTER_CFG                 := YES
CFG_FEATURE_MEMCPY_REBOOT_CFG                   := FEATURE_ON
