# Hisilicon IPP device Makefile
EXTRA_CFLAGS += -I$(srctree)/drivers/hisi/ipp/
EXTRA_CFLAGS += -I$(srctree)/drivers/hisi/ipp/include/
EXTRA_CFLAGS += -I$(srctree)/drivers/hisi/ipp/v200
EXTRA_CFLAGS += -I$(srctree)/drivers/hisi/ipp/device
EXTRA_CFLAGS += -I$(srctree)/drivers/hisi/ipp/device/include/

obj-y += cmdlst.o
obj-y += cvdr.o
obj-y += cvdr_opt.o
obj-y += smmu.o

